<?php
require_once __DIR__.'/includes/functions.php';
require_login();
$gen=$_SESSION['last_generation'] ?? null;
if(!$gen){ exit('Aucune génération disponible.'); }
$color = sanitize_color($gen['primary_color'] ?? '#2563eb');
header('Content-Type: text/html; charset=utf-8');
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><title>Fiche identifiants</title><style>
:root{--primary:<?=h($color)?>}body{font-family:Arial,sans-serif;margin:28px;color:#111;background:#fff}.sheet{max-width:940px;margin:0 auto;border:1px solid #d5dce8;border-radius:22px;padding:28px}.head{display:flex;align-items:center;gap:18px;border-bottom:4px solid var(--primary);padding-bottom:18px}.logo{width:84px;height:84px;border-radius:22px;background:var(--primary);color:#fff;display:flex;align-items:center;justify-content:center;font-size:28px;font-weight:900;overflow:hidden}.logo img{max-width:100%;max-height:100%;object-fit:contain}.head h1{margin:0;font-size:27px}.head p{margin:6px 0 0;color:#555}.hello{margin:24px 0 12px;font-size:20px;font-weight:700}.info{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0 22px}.info div{border:1px solid #d5dce8;border-radius:14px;padding:12px;background:#f8fbff}.info span{display:block;color:#667085;font-size:12px;text-transform:uppercase;font-weight:700}.info strong{display:block;margin-top:4px}table{width:100%;border-collapse:collapse;margin-top:15px;overflow:hidden;border-radius:14px}th,td{border:1px solid #cfd8e5;padding:11px;text-align:left;word-break:break-word}th{background:var(--primary);color:#fff;text-transform:uppercase;font-size:12px}.note{color:#666;font-size:12px;margin-top:18px}.no-print{margin-top:20px}.btn{border:0;border-radius:12px;background:var(--primary);color:white;padding:11px 16px;font-weight:700}@media print{.no-print{display:none}body{margin:0}.sheet{border:0;border-radius:0;max-width:none}.info{grid-template-columns:repeat(4,1fr)}}
</style></head><body><div class="sheet"><div class="head"><div class="logo"><?php if(!empty($gen['logo_url'])): ?><img src="<?=h($gen['logo_url'])?>" alt="Logo"><?php else: ?><?=h(initials_from_company($gen['company_name'] ?? 'UserFlow DEMO'))?><?php endif; ?></div><div><h1>Fiche d’arrivée utilisateur</h1><p><?=h($gen['company_name'] ?? 'UserFlow DEMO')?> · Identifiants et accès</p></div></div><div class="hello">Bienvenue <?=h($gen['full_name'] ?? (($gen['first']??'').' '.($gen['last']??'')))?></div><div class="info"><div><span>Email</span><strong><?=h($gen['email']??'')?></strong></div><div><span>Mobile</span><strong><?=h($gen['phone_mobile'] ?: '—')?></strong></div><div><span>Interne</span><strong><?=h($gen['phone_internal'] ?: '—')?></strong></div><div><span>Externe</span><strong><?=h($gen['phone_external'] ?: '—')?></strong></div></div><table><thead><tr><th>Application</th><th>URL</th><th>Identifiant</th><th>Mot de passe</th></tr></thead><tbody><?php foreach($gen['items'] as $it): ?><tr><td><?=h($it['application'])?></td><td><?php if(!empty($it['url'])): ?><?=h($it['url'])?><?php else: ?>—<?php endif; ?></td><td><?=h($it['login'])?></td><td><?=h($it['password'])?></td></tr><?php endforeach; ?></tbody></table><p class="note">Document généré automatiquement. Les scripts ne sont pas affichés dans cette fiche PDF.</p><div class="no-print"><button class="btn" onclick="window.print()">Imprimer / Enregistrer en PDF</button></div></div><script>window.onload=function(){setTimeout(function(){window.print()},300)}</script></body></html>
